file:
  reference: human_g1k_v37.fasta
  ncbi_gene: Homo_sapiens.gene_info.gz
  refgene: refgene.b37.txt
  ens_mt: ens_mt.b37.txt
  cds: refgene.cds.b37.bed
  exon: refgene.exon.b37.bed
  mrna: mRNA.b37.fasta
  refidx: refgene_ensMT.b37.idx
param:
  up_down_stream: 1000
  refidx_step: 300000
  splicing_len: 15
chrom:
  - name: 1
    length: 249250621
  - name: 2
    length: 243199373
  - name: 3
    length: 198022430
  - name: 4
    length: 191154276
  - name: 5
    length: 180915260
  - name: 6
    length: 171115067
  - name: 7
    length: 159138663
  - name: 8
    length: 146364022
  - name: 9
    length: 141213431
  - name: 10
    length: 135534747
  - name: 11
    length: 135006516
  - name: 12
    length: 133851895
  - name: 13
    length: 115169878
  - name: 14
    length: 107349540
  - name: 15
    length: 102531392
  - name: 16
    length: 90354753
  - name: 17
    length: 81195210
  - name: 18
    length: 78077248
  - name: 19
    length: 59128983
  - name: 20
    length: 63025520
  - name: 21
    length: 48129895
  - name: 22
    length: 51304566
  - name: X
    length: 155270560
  - name: Y
    length: 59373566
  - name: MT
    length: 16569