database:
  reference: human_g1k_v37.fasta
  ncbi_gene: Homo_sapiens.gene_info.gz
  refgene: refgene.b37.txt
  ensmt: ens_mt.b37.txt
  cds: refgene.cds.b37.bed
  exon: refgene.exon.b37.bed
  mrna: mRNA.b37.fasta
  refidx: refgene_ensMT.b37.idx
param:
  up_down_stream: 1e9